# Generated by Django 4.2.7 on 2023-11-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_empleado_sueldo_alter_empleado_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.puesto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.local'),
        ),
    ]
