# Generated by Django 4.2.7 on 2023-11-25 02:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_empleado_cargo_alter_empleado_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompraProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('subtotal', models.FloatField(default=0)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compra')),
                ('pastel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pasteles')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estado',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='municipio',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedor'),
        ),
    ]
